[project]
name = "dynaq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "gymnasium[box2d,toy-text]>=1.2.2",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "pygame>=2.6.1",
]
